apiVersion: v1
kind: Secret
metadata:
  name: demo-workers-user
data:
  RabbitMqHost: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xLmRldi5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: demo-workers-user
#   namespace: dev
#   labels:
#     app: demo-workers-user
# spec:
#   selector:
#     matchLabels:
#       app: demo-workers-user
#   template:
#     metadata:
#       labels:
#         app: demo-workers-user
#     spec:
#       containers:
#         - name: demo-workers-user
#           image: localhost:32000/demo-workers-user:registry
#           imagePullPolicy: IfNotPresent
#           envFrom:
#             - secretRef:
#                 name: demo-workers-user
#           env:
#             - name: RabbitMq__Host
#               value: rabbitmq.dev.svc.cluster.local
#             - name: RabbitMq__VirtualHost
#               value: /
#             - name: RabbitMq__Username
#               value: admin
#             - name: RabbitMq__Password
#               value: admin
#             - name: Serilog__WriteTo__0__Args__serverUrl
#               value: 'http://my-seq.dev:5341'
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: demo-workers-user
  namespace: dev
  labels:
    deploymentName: demo-workers-user
spec:
  scaleTargetRef:
    deploymentName: demo-workers-user
  pollingInterval: 5   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  maxReplicaCount: 30  # Optional. Default: 100
  triggers:
  - type: rabbitmq
    metadata:
      queueName: Demo.Workers.User.UserCreatedConsumer
      host: RabbitMqHost
      queueLength  : '5'
---